apiVersion: v2
appVersion: "1.0"
description: A Helm chart for hmc-hmi-outbound-adapter App
name: hmc-hmi-outbound-adapter
home: https://github.com/hmcts/hmc-hmi-outbound-adapter
version: 0.1.2
maintainers:
  - name: HMCTS CCD Dev Team
dependencies:
  - name: java
    version: 3.7.3
    repository: '@hmctspublic'
  - name: servicebus
    version: 0.3.0
    repository: '@hmctspublic'
    condition: servicebus.enabled
