java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    HMC_SERVICE_BUS_OUTBOUND_QUEUE: hmc-to-hmi
    HMC_SERVICE_BUS_INBOUND_QUEUE: hmc-from-hmi
  secrets:
    HMC_SERVICE_BUS_OUTBOUND_CONNECTION_STRING:
      secretRef: hmc-sb-preview
      key: connectionString
    HMC_SERVICE_BUS_INBOUND_CONNECTION_STRING:
      secretRef: hmc-sb-preview
      key: connectionString
  keyVaults:
    hmc:
      resourceGroup: hmc-shared
      secrets:
        - name: AppInsightsInstrumentationKey

hmc:
  enabled: true
  hmc:
    servicebus:
      enabled: true
    hearingService:
      enabled: true
    inboundAdapter:
      enabled: false
    outboundAdapter:
      enabled: false

  hmc-cft-hearing-service:
    HMC_SERVICE_BUS_TOPIC: hmc-to-cft
    HMC_SERVICE_BUS_SUBSCRIPTION: hmc-subs-to-cft
    HMC_SERVICE_BUS_QUEUE: hmc-from-hmi
    HMC_OUTBOUND_SERVICE_BUS_QUEUE: hmc-to-hmi
    CFT_HEARING_SERVICE_DB_HOST: "{{ .Release.Name }}-postgresql"
    CFT_HEARING_SERVICE_DB_NAME: "{{ .Values.postgresql.auth.database}}"
    CFT_HEARING_SERVICE_DB_USERNAME: "{{ .Values.postgresql.auth.username}}"
    CFT_HEARING_SERVICE_DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    CFT_HEARING_SERVICE_DB_OPTIONS: "?stringtype=unspecified"
    CFT_HEARING_SERVICE_DB_PORT: 5432
    CCD_DATA_STORE_API_BASE_URL: "http://ccd-test-stubs-service-aat.service.core-compute-aat.internal"

servicebus:
  enabled: true
  teamName: CCD
  resourceGroup: hmc-aso-preview-rg
  sbNamespace: hmc-sb-preview
  setup:
    queues:
      - name: hmc-to-hmi
      - name: hmc-from-hmi
